In [2]:
import numpy as np

In [3]:
population = np.random.randint(0,80,100000) #the ages of a population

In [4]:
population[0:10]

array([ 2,  4,  2, 79, 62, 57, 42, 48, 25, 24])

In [14]:
#a sample
np.random.seed(115) #it provides the unchancing random values for every call
sample = np.random.choice(a=population,size=100)
sample[0:10]

array([55, 64, 35, 16,  0,  6, 15, 78, 37, 76])

In [12]:
sample.mean()

np.float64(39.46)

In [7]:
population.mean()

np.float64(39.62266)

In [37]:
np.random.seed(10)
s = []
for i in range(10):
    s.append(np.random.choice(a=population, size=100))
s

[array([29,  7, 75, 42, 16, 42, 31, 14, 13,  3,  8, 10, 43, 28, 41, 77, 32,
        54, 53,  8, 35, 14, 10, 62, 63, 38, 40, 69, 35, 79,  0, 11, 60, 77,
        57, 66, 69, 61, 23, 19, 64, 43, 34, 74, 17, 39, 42, 21, 23, 41, 45,
        56, 30, 30, 49, 42, 15, 48, 68, 37, 56,  7, 55, 65, 55, 21, 44, 50,
         9, 12, 42, 10, 78, 31, 51, 62,  4, 76, 13, 18, 37, 59, 73,  3, 44,
        55, 45, 71, 64, 44, 57, 53,  2, 51, 61, 45, 46, 75, 18, 28]),
 array([37, 24, 75, 34, 19, 73, 20, 29, 15, 74, 43, 33, 46, 52,  7, 59, 42,
        69, 30, 57, 19, 47, 71, 40, 59, 78,  6,  3, 58, 14, 73, 59, 54, 19,
        60,  1, 40, 45,  9, 20, 43, 65, 41, 57, 26, 72, 30, 78, 12, 13, 30,
         4, 49, 28, 37, 64,  1, 56, 30,  7, 59, 79, 61, 53, 64, 34, 44, 21,
        20, 68, 17, 57,  5, 11, 55, 61, 57, 51, 46, 28, 20, 34, 62, 31, 43,
        13, 21,  9, 35, 39, 10, 57, 79, 73, 59, 15, 50,  3, 43, 17]),
 array([38, 48,  5, 72, 68, 29, 52, 12, 77, 31,  2, 72, 41,  0, 70, 62, 49,
        12, 38, 11, 12, 

In [33]:
s[0].mean()

np.float64(40.22)

In [34]:
s[2].mean()

np.float64(41.57)

In [39]:
sum_of_mean=0
for i in s:
    sum_of_mean += i.mean()
sum_of_mean / 10

np.float64(39.763999999999996)