# 🔍 Pandas DataFrame Element Operations

#### » Import the Pandas and Numpy libraries

In [1]:
import pandas as pd
import numpy as np

#### » Create random integer arrays using Numpy

In [2]:
v1 = np.random.randint(5, size=5)
v2 = np.random.randint(5, size=5)
v3 = np.random.randint(5, size=5)

In [3]:
v1

array([3, 4, 3, 0, 4])

In [4]:
v2

array([0, 0, 1, 2, 2])

In [5]:
v3

array([0, 3, 2, 2, 4])

#### » Create a dictionary of column names and NumPy arrays

In [6]:
dic = {"var1": v1, "var2": v2, "var3": v3}
dic

{'var1': array([3, 4, 3, 0, 4]),
 'var2': array([0, 0, 1, 2, 2]),
 'var3': array([0, 3, 2, 2, 4])}

#### » Create a DataFrame from the dictionary

In [7]:
df = pd.DataFrame(dic)
df

var1  var2  var3
0     3     0     0
1     4     0     3
2     3     1     2
3     0     2     2
4     4     2     4

#### » View the current index labels

In [8]:
df.index

RangeIndex(start=0, stop=5, step=1)

#### » Set custom row labels to the index

In [9]:
df.index = ["a","b","c","d","e"]
df.index

Index(['a', 'b', 'c', 'd', 'e'], dtype='object')

In [10]:
df

var1  var2  var3
a     3     0     0
b     4     0     3
c     3     1     2
d     0     2     2
e     4     2     4

#### » Drop the row with a label (not permanent) `dataframe.drop(label)`

In [11]:
df.drop("a", axis=0)

var1  var2  var3
b     4     0     3
c     3     1     2
d     0     2     2
e     4     2     4

In [12]:
df

var1  var2  var3
a     3     0     0
b     4     0     3
c     3     1     2
d     0     2     2
e     4     2     4

#### » Drop the row with a label (permanent) -> `dataframe.drop(label,inplace=True)`

In [13]:
df.drop("a", axis=0, inplace=True)
df

var1  var2  var3
b     4     0     3
c     3     1     2
d     0     2     2
e     4     2     4

#### » Drop rows with a label list (not permanent)

In [14]:
l = ["b", "d"]
df.drop(l, axis=0)

var1  var2  var3
c     3     1     2
e     4     2     4

#### » Create a new column using other columns

In [15]:
df["var4"] = df["var2"]*df["var3"]
df

var1  var2  var3  var4
b     4     0     3     0
c     3     1     2     2
d     0     2     2     4
e     4     2     4     8

#### » Drop the column with a label (not permanent) `dataframe.drop(label,axis=1)`

In [16]:
df.drop("var4", axis=1)

var1  var2  var3
b     4     0     3
c     3     1     2
d     0     2     2
e     4     2     4

In [17]:
df

var1  var2  var3  var4
b     4     0     3     0
c     3     1     2     2
d     0     2     2     4
e     4     2     4     8

#### » Drop the column with a label (permanent) -> `dataframe.drop(label,axis=1,inplace=True)`

In [18]:
df.drop("var4", axis=1, inplace=True)
df

var1  var2  var3
b     4     0     3
c     3     1     2
d     0     2     2
e     4     2     4

#### » Check if column label exists in the DataFrame

In [19]:
"var1" in df

True