In [6]:
import pandas as pd

In [7]:
import numpy as np

In [28]:
v1 = np.random.randint(5, size=5)
v2 = np.random.randint(5, size=5)
v3 = np.random.randint(5, size=5)

In [29]:
v1

array([1, 1, 2, 2, 0])

In [30]:
v2

array([4, 4, 4, 4, 1])

In [31]:
v3

array([3, 0, 1, 3, 0])

In [32]:
dic = {"var1": v1, "var2": v2, "var3": v3}

In [33]:
dic

{'var1': array([1, 1, 2, 2, 0]),
 'var2': array([4, 4, 4, 4, 1]),
 'var3': array([3, 0, 1, 3, 0])}

In [34]:
df = pd.DataFrame(dic)

In [35]:
df

var1  var2  var3
0     1     4     3
1     1     4     0
2     2     4     1
3     2     4     3
4     0     1     0

In [37]:
df[0:1]

var1  var2  var3
0     1     4     3

In [38]:
df.index

RangeIndex(start=0, stop=5, step=1)

In [39]:
df.index = ["a","b","c","d","e"]

In [40]:
df

var1  var2  var3
a     1     4     3
b     1     4     0
c     2     4     1
d     2     4     3
e     0     1     0

In [41]:
df.drop("a", axis=0)

var1  var2  var3
b     1     4     0
c     2     4     1
d     2     4     3
e     0     1     0

In [42]:
df

var1  var2  var3
a     1     4     3
b     1     4     0
c     2     4     1
d     2     4     3
e     0     1     0

In [43]:
df.drop("a", axis=0, inplace=True)

In [44]:
df

var1  var2  var3
b     1     4     0
c     2     4     1
d     2     4     3
e     0     1     0

In [47]:
l = ["b", "d"]

In [48]:
df.drop(l, axis=0)

var1  var2  var3
c     2     4     1
e     0     1     0

In [49]:
"var1" in df

True

In [50]:
df["var4"] = df["var2"]*df["var3"]

In [51]:
df

var1  var2  var3  var4
b     1     4     0     0
c     2     4     1     4
d     2     4     3    12
e     0     1     0     0

In [52]:
df.drop("var4", axis=1)

var1  var2  var3
b     1     4     0
c     2     4     1
d     2     4     3
e     0     1     0

In [53]:
df

var1  var2  var3  var4
b     1     4     0     0
c     2     4     1     4
d     2     4     3    12
e     0     1     0     0

In [54]:
df.drop("var4", axis=1, inplace=True)

In [55]:
df

var1  var2  var3
b     1     4     0
c     2     4     1
d     2     4     3
e     0     1     0