In [1]:
import numpy as np
import pandas as pd
vector1 = np.array([2,7,4,9,1])
vector2 = np.array([4,2,7,8,7])
vector3 = np.array([5,4,8,12,5])
df = pd.DataFrame({"V1":vector1,"V2":vector2,"V3":vector3})
df = df.astype(float)
df

V1   V2    V3
0  2.0  4.0   5.0
1  7.0  2.0   4.0
2  4.0  7.0   8.0
3  9.0  8.0  12.0
4  1.0  7.0   5.0

In [2]:
from sklearn import preprocessing

In [3]:
preprocessing.scale(df) #mean: 0, std var:1

array([[-0.86474714, -0.71269665, -0.61522733],
       [ 0.79822813, -1.60356745, -0.9570203 ],
       [-0.19955703,  0.62360956,  0.41015156],
       [ 1.46341823,  1.06904497,  1.77732341],
       [-1.19734219,  0.62360956, -0.61522733]])

In [5]:
#normalization
preprocessing.normalize(df)

array([[0.2981424 , 0.59628479, 0.74535599],
       [0.84270097, 0.24077171, 0.48154341],
       [0.35218036, 0.61631563, 0.70436073],
       [0.52941176, 0.47058824, 0.70588235],
       [0.11547005, 0.80829038, 0.57735027]])

In [6]:
#min-max
scaler = preprocessing.MinMaxScaler(feature_range=(10,20))

In [7]:
scaler.fit_transform(df)

array([[11.25      , 13.33333333, 11.25      ],
       [17.5       , 10.        , 10.        ],
       [13.75      , 18.33333333, 15.        ],
       [20.        , 20.        , 20.        ],
       [10.        , 18.33333333, 11.25      ]])

In [8]:
#binarize
binarizer = preprocessing.Binarizer(threshold=5).fit(df)

In [9]:
binarizer.transform(df)

array([[0., 0., 0.],
       [1., 0., 0.],
       [0., 1., 1.],
       [1., 1., 1.],
       [0., 1., 0.]])