# 🎯 NumPy Element Access

#### » Import the NumPy library, usually abbreviated as `np`

In [2]:
import numpy as np

#### » Create 1D array with 10 random integer values

In [3]:
a = np.random.randint(10, size=10)
a

array([7, 1, 7, 6, 4, 1, 3, 1, 3, 8])

#### » Access the nth element of a 1D array -> `array[n]`

In [4]:
a[2]

np.int64(7)

#### » Access the last element of a 1D array

In [5]:
a[-1]

np.int64(8)

#### » Set the nth element of the array to x -> `array[n]=x`

In [6]:
a[0] = 20
a

array([20,  1,  7,  6,  4,  1,  3,  1,  3,  8])

#### » Create 2D array with 4 random integer values

In [7]:
b = np.random.randint(10, size=(2,2))
b

array([[1, 2],
       [5, 4]])

#### » Access element in xth row, yth column of a 2D array -> `array[x,y]`

In [8]:
b[0,0]

np.int64(1)

#### » Set the element in the xth row, yth column of a 2D array to n -> `array[x,y] = n`

In [9]:
b[0,1] = 10.2
b

array([[ 1, 10],
       [ 5,  4]])