# 🎯 NumPy Element Access

#### » Importing the NumPy library, usually abbreviated as `np`

In [1]:
import numpy as np

#### » Creating 1D array with 10 random integer values

In [2]:
a = np.random.randint(10, size=10)

In [3]:
a

array([4, 9, 1, 3, 3, 7, 0, 8, 7, 0])

#### » Accessing the nth element of a 1D array -> `array[n]`

In [4]:
a[2]

np.int64(1)

#### » Accessing the last element of a 1D array

In [5]:
a[-1]

np.int64(0)

#### » Setting the nth element of the array to x -> `array[n]=x`

In [6]:
a[0] = 20

In [7]:
a

array([20,  9,  1,  3,  3,  7,  0,  8,  7,  0])

#### » Creating 2D array with 4 random integer values

In [8]:
b = np.random.randint(10, size=(2,2))

In [9]:
b

array([[3, 4],
       [1, 9]])

#### » Accessing element in xth row, yth column of a 2D array -> `array[x,y]`

In [10]:
b[0,0]

np.int64(3)

#### » Setting the element in the xth row, yth column of a 2D array to n -> `array[x,y] = n`

In [11]:
b[0,1] = 10.2

In [12]:
b

array([[ 3, 10],
       [ 1,  9]])