# 🔗 NumPy Array Concatenation

#### » Import the NumPy library, usually abbreviated as `np`

In [1]:
import numpy as np

#### » Concatenate 1D arrays

In [9]:
x = np.array([1,2,3])
y = np.array([4,5,6])
np.concatenate([x,y])

array([1, 2, 3, 4, 5, 6])

In [10]:
z = np.array([7,8,9])
np.concatenate([x,y,z])

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

#### » Concatenate 2D arrays

In [11]:
a = np.array([[1,2,3],
              [4,5,6]])
np.concatenate([a,a])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

#### » Concatenate 2D arrays along rows (axis=0)

In [12]:
np.concatenate([a,a], axis=0)

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

#### » Concatenate 2D arrays along columns (axis=1)

In [13]:
np.concatenate([a,a], axis=1)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

#### » Stack arrays along a new axis

In [14]:
np.stack([a, a], axis=0)

array([[[1, 2, 3],
        [4, 5, 6]],

       [[1, 2, 3],
        [4, 5, 6]]])

#### » Horizontally stack arrays (columns)

In [15]:
np.hstack([a, a])

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

#### » Vertically stack arrays (rows)

In [18]:
np.vstack([a, a])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])