In [1]:
import numpy as np

In [7]:
#Single Dimension

In [2]:
x = np.array([1,2,3])

In [3]:
y = np.array([4,5,6])

In [4]:
np.concatenate([x,y])

array([1, 2, 3, 4, 5, 6])

In [5]:
z = np.array([7,8,9])

In [6]:
np.concatenate([x,y,z])

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
#Two Dimensions

In [9]:
a = np.array([[1,2,3],
              [4,5,6]])

In [10]:
np.concatenate([a,a])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [12]:
np.concatenate([a,a], axis=0) #concatenation with rows

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [13]:
np.concatenate([a,a], axis=1) #concatenation with columns

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])