# ✅ NumPy Conditional Element Selection

#### » Import the NumPy library, usually abbreviated as `np`

In [1]:
import numpy as np

#### » Create 1D array using `arange` 

In [2]:
v = np.arange(1,6)
v

array([1, 2, 3, 4, 5])

#### » Create a boolean mask where elements are less or greater than n -> `array<n or array>n`

In [3]:
v < 3

array([ True,  True, False, False, False])

In [4]:
v > 4

array([False, False, False, False,  True])

#### » Get elements less or greater than n -> `array[array<n] or array[array>n]`

In [5]:
v[v < 3]

array([1, 2])

In [6]:
v[v >= 3]

array([3, 4, 5])

#### » Select all elements that are not equal to n -> `array[array != n]`

In [10]:
v[v != 3]

array([1, 2, 4, 5])

#### » Get elements that are even

In [10]:
v[v % 2 == 0]

array([2, 4])

#### » Combine conditions with `& (and)` 

In [11]:
v[(v > 2) & (v < 5)]

array([3, 4])

#### » Use `~`  to invert condition (not)

In [7]:
v[~(v > 5)] #same as v[v <= 5]

array([1, 2, 3, 4, 5])

#### » Modify elements

In [8]:
v[v < 3] = 0
v

array([0, 0, 3, 4, 5])