In [1]:
import numpy as np

In [2]:
a = np.random.randint(10, size=10)

In [3]:
a

array([4, 9, 1, 3, 3, 7, 0, 8, 7, 0])

In [4]:
a[2]

np.int64(1)

In [5]:
a[-1]

np.int64(0)

In [6]:
a[0] = 20

In [7]:
a

array([20,  9,  1,  3,  3,  7,  0,  8,  7,  0])

In [8]:
b = np.random.randint(10, size=(2,2))

In [9]:
b

array([[3, 4],
       [1, 9]])

In [10]:
b[0,0]

np.int64(3)

In [11]:
b[0,1] = 10.2

In [12]:
b

array([[ 3, 10],
       [ 1,  9]])