In [1]:
import numpy as np

5 * x0 + x1 = 12

x0 + 3 * x1 = 10

In [ ]:
#multiplier of unknown variables

In [2]:
a = np.array([[5,1], [1,3]])

In [3]:
a

array([[5, 1],
       [1, 3]])

In [9]:
#multiplier of results

In [4]:
b = np.array([12,10])

In [5]:
b

array([12, 10])

In [10]:
#Finding values of unknown variables using linear algebra

In [6]:
x = np.linalg.solve(a,b)

In [7]:
x

array([1.85714286, 2.71428571])