# ❓ Solving a System of Linear Equations with NumPy

We are solving the following system of equations:

5 * x0 + x1 = 12
x0 + 3 * x1 = 10

We’ll use `np.linalg.solve()` to find values of unknown variables x₀ and x₁

#### » Import the NumPy library, usually abbreviated as `np`

In [1]:
import numpy as np

#### » Coefficient matrix of unknowns (x0 and x1)

In [2]:
a = np.array([[5,1], [1,3]])
a

array([[5, 1],
       [1, 3]])

#### » Result vector (right-hand side of equations)

In [3]:
b = np.array([12,10])
b

array([12, 10])

#### » Finding values of unknown variables using `linear algebra` 

In [4]:
x = np.linalg.solve(a,b)
x

array([1.85714286, 2.71428571])