In [1]:
import numpy as np

In [2]:
a = np.arange(0,10,2)

In [3]:
a

array([0, 2, 4, 6, 8])

In [4]:
[a[1], a[3], a[4]]

[np.int64(2), np.int64(6), np.int64(8)]

In [5]:
list_a = [1,3,4]

In [6]:
a[list_a]

array([2, 6, 8])

In [7]:
b = np.arange(6).reshape(2,3)

In [8]:
b

array([[0, 1, 2],
       [3, 4, 5]])

In [9]:
row = np.array([0,1])

In [10]:
column = np.array([1,2])

In [11]:
b[row, column]

array([1, 5])

In [12]:
#Fancy indext with basic index

In [13]:
b[0, [1,2]]

array([1, 2])

In [14]:
#Fancy indext with slice

In [16]:
b[0:, [1,2]]

array([[1, 2],
       [4, 5]])