# ✨ NumPy Fancy Indexing

#### » Import the NumPy library, usually abbreviated as `np`

In [1]:
import numpy as np

#### » Create 1D array using `arange` 

In [2]:
a = np.arange(0,10,2)
a

array([0, 2, 4, 6, 8])

#### » Select elements at index 1, 3, and 4

In [3]:
[a[1], a[3], a[4]]

[np.int64(2), np.int64(6), np.int64(8)]

In [4]:
a[[1,3,4]]

array([2, 6, 8])

In [5]:
list_a = [1,3,4]
a[list_a]

array([2, 6, 8])

#### » Create 1D array using `arange` and reshaping it to 2D 

In [6]:
b = np.arange(6).reshape(2,3)
b

array([[0, 1, 2],
       [3, 4, 5]])

In [7]:
row = np.array([0,1])
column = np.array([1,2])

#### » Select specific elements by row and column

In [8]:
b[row, column]

array([1, 5])

#### » Fancy indexing with `basic index` 

In [13]:
b[0, [1,2]]

array([1, 2])

#### » Fancy indexing with `slicing` 

In [16]:
b[0:, [1,2]]

array([[1, 2],
       [4, 5]])