# Numpy

In [3]:
import numpy as np

In [4]:
np.array([1,2,3,4,5])

array([1, 2, 3, 4, 5])

In [5]:
a = np.array([1,2,3,4,5])

In [6]:
type(a)

numpy.ndarray

In [7]:
np.array([3.14, 4, 2, 13])

array([ 3.14,  4.  ,  2.  , 13.  ])

In [10]:
np.array([3.14, 4, 2, 13], dtype="float")

array([ 3.14,  4.  ,  2.  , 13.  ])

In [9]:
np.array([3.14, 4, 2, 13], dtype="int")

array([ 3,  4,  2, 13])

In [12]:
np.zeros(10, dtype="int")

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [13]:
np.ones((3,5), dtype="int")

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [14]:
np.full((3,5), 5)

array([[5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5]])

In [15]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [16]:
np.linspace(0,1,10)

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

In [19]:
np.random.normal(10, 4, (2,2))

array([[ 8.77616461,  6.42736491],
       [ 6.6251202 , 14.96411356]])

In [18]:
np.random.randint(0,10,(2,5))

array([[9, 4, 3, 2, 1],
       [9, 2, 8, 6, 1]])