# 📘 NumPy Introduction

**NumPy (Numerical Python)** is a powerful Python library for numerical computations. It is used for working with arrays, matrices, and offers a wide variety of mathematical functions.

#### » Importing the NumPy library, usually abbreviated as `np`

In [2]:
import numpy as np

 #### » Creating a simple 1D NumPy array of integers

In [33]:
np.array([1,2,3,4,5])

array([1, 2, 3, 4, 5])

 #### » Creating a simple 2D NumPy array of integers

In [36]:
np.array([[1,2,3,4,5],[3,4,5,6,7]])

array([[1, 2, 3, 4, 5],
       [3, 4, 5, 6, 7]])

#### » Creating a NumPy array with mixed integer and float elements. NumPy will upcast them to float

In [7]:
np.array([3.14, 4, 2, 13])

array([ 3.14,  4.  ,  2.  , 13.  ])

#### » Setting the data type (`dtype`) to float,int,complex etc. when creating the array

In [10]:
np.array([3.14, 4, 2, 13], dtype="float")

array([ 3.14,  4.  ,  2.  , 13.  ])

In [9]:
np.array([3.14, 4, 2, 13], dtype="int")

array([ 3,  4,  2, 13])

#### » Another way to set array type is using `astype`

In [5]:
np.array([3.14, 4, 2, 13]).astype("int")

array([ 3,  4,  2, 13])

#### » Creating a NumPy array filled with 0

In [12]:
np.zeros(10, dtype="int")

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

#### » Creating a NumPy array filled with 1

In [13]:
np.ones((3,5), dtype="int")

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

#### » Creating a NumPy array filled with n -> `np.full(size,n)`

In [14]:
np.full((3,5), 5)

array([[5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5]])

#### » Creating a NumPy array with a range -> `np.arange(start=0,stop,step=1)`

In [6]:
np.arange(20)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [39]:
np.arange(2,10,2)

array([2, 4, 6, 8])

#### » Creating a NumPy array of evenly spaced values over a specified interval

In [16]:
np.linspace(0,1,10)

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

#### » Creating an array with values sampled from a `normal (Gaussian) distribution`

In [7]:
np.random.normal(10, 4, (2,2)) #(mean,std,size)

array([[ 7.37047629,  8.12608609],
       [16.92203076,  9.59512279]])

#### » Creating an array of random integers from a given range

In [41]:
np.random.randint(10)

9

In [40]:
np.random.randint(0,10,5) #(start,stop,size)

array([1, 2, 7, 4, 7])

In [18]:
np.random.randint(0,10,(2,5))

array([[9, 4, 3, 2, 1],
       [9, 2, 8, 6, 1]])

#### » Checking if all elements in an array are True

In [11]:
np.all([-1, 4, 5]) #is all elemets true?

np.True_

In [12]:
np.all([-1, 0, 5])

np.False_

In [13]:
np.all([True,False])

np.False_

In [14]:
np.all([True,True])

np.True_

#### » Creating an identity matrix with 1s on the `diagonal`

In [22]:
np.eye(5, dtype=int)

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

In [25]:
np.eye(5, dtype=int, k=-1)

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0]])

In [26]:
np.eye(5, dtype=int, k=2)

array([[0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])