In [1]:
import numpy as np

In [2]:
v = np.arange(1,6)

In [8]:
v

array([1, 2, 3, 4, 5])

In [3]:
#ufunc

In [6]:
np.subtract(v, 1)

array([0, 1, 2, 3, 4])

In [7]:
v -1

array([0, 1, 2, 3, 4])

In [9]:
np.add(v, 1)

array([2, 3, 4, 5, 6])

In [10]:
v + 1

array([2, 3, 4, 5, 6])

In [11]:
np.multiply(v, 4)

array([ 4,  8, 12, 16, 20])

In [12]:
v * 4

array([ 4,  8, 12, 16, 20])

In [13]:
np.divide(v, 3)

array([0.33333333, 0.66666667, 1.        , 1.33333333, 1.66666667])

In [14]:
v /3 

array([0.33333333, 0.66666667, 1.        , 1.33333333, 1.66666667])

In [15]:
np.power(v, 2)

array([ 1,  4,  9, 16, 25])

In [16]:
v ** 2

array([ 1,  4,  9, 16, 25])

In [17]:
np.mod(v, 2)

array([1, 0, 1, 0, 1])

In [18]:
v % 2

array([1, 0, 1, 0, 1])

In [21]:
np.absolute(np.array([-3]))

array([3])

In [22]:
np.sin(360)

np.float64(0.9589157234143065)

In [23]:
np.cos(90)

np.float64(-0.4480736161291702)

In [24]:
np.log(2)

np.float64(0.6931471805599453)

In [25]:
np.log(v)

array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791])

In [26]:
np.log2(v)

array([0.        , 1.        , 1.5849625 , 2.        , 2.32192809])

In [27]:
np.log10(v)

array([0.        , 0.30103   , 0.47712125, 0.60205999, 0.69897   ])

In [28]:
?np

Type:        module
String form: <module 'numpy' from '/opt/anaconda3/lib/python3.13/site-packages/numpy/__init__.py'>
File:        /opt/anaconda3/lib/python3.13/site-packages/numpy/__init__.py
Docstring:  
NumPy
=====

Provides
  1. An array object of arbitrary homogeneous items
  2. Fast mathematical operations over arrays
  3. Linear Algebra, Fourier Transforms, Random Number Generation

How to use the documentation
----------------------------
Documentation is available in two forms: docstrings provided
with the code, and a loose standing reference guide, available from
`the NumPy homepage <https://numpy.org>`_.

We recommend exploring the docstrings using
`IPython <https://ipython.org>`_, an advanced Python shell with
TAB-completion and introspection capabilities.  See below for further
instructions.

The docstring examples assume that `numpy` has been imported as ``np``::

  >>> import numpy as np

Code snippets are indicated by three greater-than signs::

  >>> x = 42
  >>> x = 