# 🔄 NumPy Reshaping

#### » Importing the NumPy library, usually abbreviated as `np`

In [3]:
import numpy as np

#### » Creating a 1D array of 9 elements

In [4]:
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

#### » Reshaping to 2D (3 rows, 3 columns)

In [5]:
np.arange(1,10).reshape((3,3))

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [22]:
a = np.arange(1,10) #a vector

In [7]:
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
a.ndim

1

In [23]:
b = a.reshape((1,9)) #a matrix

In [24]:
b

array([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [11]:
b.ndim

2

#### » Flattening the array into 1D (returns a copy)

In [29]:
b.flatten()

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [33]:
b

array([[1, 2, 3, 4, 5, 6, 7, 8, 9]])