# 🔄 NumPy Reshaping

#### » Import the NumPy library, usually abbreviated as `np`

In [1]:
import numpy as np

#### » Create a 1D array of 9 elements

In [2]:
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

#### » Reshape to 2D (3 rows, 3 columns)

In [3]:
np.arange(1,10).reshape((3,3))

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [8]:
a = np.arange(1,10) #vector
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
a.ndim

1

In [7]:
b = a.reshape((1,9)) #matrix
b

array([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [9]:
b.ndim

2

#### » Flattens the array into 1D (returns a copy)

In [10]:
b.flatten()

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
b

array([[1, 2, 3, 4, 5, 6, 7, 8, 9]])