# ✂️ NumPy Array Slicing

#### » Import the NumPy library, usually abbreviated as `np`

In [1]:
import numpy as np

#### » Create 1D array using `arange` function

In [2]:
a = np.arange(20,30)
a

array([20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

#### » Get all elements starting from index n to the end -> `array[n:]`

In [3]:
a[3:]

array([23, 24, 25, 26, 27, 28, 29])

#### » Get elements from start up to (but not including) index n -> `array[:n]`

In [4]:
a[:3]

array([20, 21, 22])

#### » Get elements from index x up to (but not including) index y -> `array[x,y]`

In [5]:
a[1:2]

array([21])

In [6]:
a[3:6]

array([23, 24, 25])

#### » Get every nth element starting from given index -> `array[start,stop,step]`

In [7]:
a[1::2]

array([21, 23, 25, 27, 29])

#### » Create 2D array of random integers from a given range¶

In [8]:
b = np.random.randint(10, size=(5,5))
b

array([[6, 8, 6, 6, 1],
       [6, 8, 7, 3, 7],
       [6, 2, 5, 0, 2],
       [4, 0, 0, 9, 0],
       [9, 6, 0, 1, 8]])

#### » Get all rows from the nth column of a 2D array -> `array[:,n]` 

In [9]:
b[:,0]

array([6, 6, 6, 4, 9])

In [10]:
b[:0]

array([], shape=(0, 5), dtype=int64)

In [11]:
b[:,1]

array([8, 8, 2, 0, 6])

#### » Get all columns from the nth row of a 2D array -> `array[n,:]` 

In [12]:
b[0,:]

array([6, 8, 6, 6, 1])

In [13]:
b[0]

array([6, 8, 6, 6, 1])

In [14]:
b[2,:]

array([6, 2, 5, 0, 2])

#### » Get rows 0 and 1, and only column 0 (as 2D subarray)

In [15]:
b[0:2, 0:1]

array([[6],
       [6]])

#### » Get rows 1 and 2, and columns 0 and 1

In [16]:
b[1:3, 0:2]

array([[6, 8],
       [6, 2]])

#### » Get all rows and columns 0 and 1

In [17]:
b[::, :2]

array([[6, 8],
       [6, 8],
       [6, 2],
       [4, 0],
       [9, 6]])

#### » Get all columns and rows 1 and 2

In [18]:
b[1:3, ::]

array([[6, 8, 7, 3, 7],
       [6, 2, 5, 0, 2]])

### ✶ Slicing returns a view, not a copy — changes affect original array. To prevent this, we can use `.copy()`  to create an independent array

In [19]:
subset_b = b[0:2,2:4]
subset_b

array([[6, 6],
       [7, 3]])

In [20]:
subset_b[0,0] = 99
subset_b

array([[99,  6],
       [ 7,  3]])

In [21]:
b

array([[ 6,  8, 99,  6,  1],
       [ 6,  8,  7,  3,  7],
       [ 6,  2,  5,  0,  2],
       [ 4,  0,  0,  9,  0],
       [ 9,  6,  0,  1,  8]])

In [22]:
c = np.random.randint(10, size=(5,5))
c

array([[9, 4, 0, 8, 5],
       [2, 4, 2, 9, 9],
       [8, 1, 8, 0, 6],
       [8, 4, 7, 9, 9],
       [0, 4, 9, 0, 0]])

In [23]:
alt_c = c[0:3,0:2].copy()
alt_c

array([[9, 4],
       [2, 4],
       [8, 1]])

In [24]:
alt_c[0,0] = 99
alt_c

array([[99,  4],
       [ 2,  4],
       [ 8,  1]])

In [25]:
c

array([[9, 4, 0, 8, 5],
       [2, 4, 2, 9, 9],
       [8, 1, 8, 0, 6],
       [8, 4, 7, 9, 9],
       [0, 4, 9, 0, 0]])