In [1]:
import numpy as np

In [2]:
a = np.arange(20,30)

In [3]:
a

array([20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [4]:
a[3:]

array([23, 24, 25, 26, 27, 28, 29])

In [5]:
a[1:2]

array([21])

In [6]:
a[1::2]

array([21, 23, 25, 27, 29])

In [7]:
b = np.random.randint(10, size=(5,5))

In [8]:
b

array([[6, 2, 8, 6, 7],
       [0, 1, 5, 2, 6],
       [5, 9, 6, 0, 6],
       [0, 1, 7, 2, 6],
       [3, 4, 4, 7, 7]])

In [9]:
b[:,0]

array([6, 0, 5, 0, 3])

In [10]:
b[:,1]

array([2, 1, 9, 1, 4])

In [11]:
b[0,:]

array([6, 2, 8, 6, 7])

In [12]:
b[0]

array([6, 2, 8, 6, 7])

In [13]:
b[2,:]

array([5, 9, 6, 0, 6])

In [14]:
b[0:2, 0:1]

array([[6],
       [0]])

In [15]:
b[::, :2]

array([[6, 2],
       [0, 1],
       [5, 9],
       [0, 1],
       [3, 4]])

In [16]:
b[1:3, 0:2]

array([[0, 1],
       [5, 9]])

In [17]:
b[0:2,2:4]

array([[8, 6],
       [5, 2]])

In [18]:
subset_b = b[0:2,2:4]

In [19]:
subset_b

array([[8, 6],
       [5, 2]])

In [20]:
subset_b[0,0] = 99

In [21]:
subset_b

array([[99,  6],
       [ 5,  2]])

In [22]:
b

array([[ 6,  2, 99,  6,  7],
       [ 0,  1,  5,  2,  6],
       [ 5,  9,  6,  0,  6],
       [ 0,  1,  7,  2,  6],
       [ 3,  4,  4,  7,  7]])

In [23]:
c = np.random.randint(10, size=(5,5))

In [24]:
c

array([[6, 9, 7, 8, 9],
       [2, 0, 5, 7, 4],
       [2, 9, 6, 1, 4],
       [5, 3, 3, 9, 5],
       [3, 1, 7, 7, 3]])

In [25]:
alt_c = c[0:3,0:2].copy()

In [26]:
alt_c

array([[6, 9],
       [2, 0],
       [2, 9]])

In [27]:
alt_c[0,0] = 99

In [28]:
alt_c

array([[99,  9],
       [ 2,  0],
       [ 2,  9]])

In [29]:
c

array([[6, 9, 7, 8, 9],
       [2, 0, 5, 7, 4],
       [2, 9, 6, 1, 4],
       [5, 3, 3, 9, 5],
       [3, 1, 7, 7, 3]])