In [1]:
import numpy as np

In [2]:
a = np.array([1,4,8,2,9])

In [3]:
np.sort(a)

array([1, 2, 4, 8, 9])

In [6]:
a

array([1, 2, 4, 8, 9])

In [4]:
a.sort()

In [5]:
a

array([1, 2, 4, 8, 9])

In [7]:
b = np.random.normal(10,5,(2,2))

In [8]:
b

array([[ 4.83220129, 14.77692302],
       [12.1255818 ,  7.92956543]])

In [9]:
np.sort(b, axis=0)

array([[ 4.83220129,  7.92956543],
       [12.1255818 , 14.77692302]])

In [10]:
np.sort(b, axis=1)

array([[ 4.83220129, 14.77692302],
       [ 7.92956543, 12.1255818 ]])