# 🔢 NumPy Array Sorting

#### » Importing the NumPy library, usually abbreviated as `np`

In [3]:
import numpy as np

#### » Creating a 1D array

In [4]:
a = np.array([1,4,8,2,9])

In [5]:
a

array([1, 4, 8, 2, 9])

#### » Sorting a 1D array in ascending order

In [6]:
np.sort(a)

array([1, 2, 4, 8, 9])

In [6]:
a

array([1, 2, 4, 8, 9])

In [8]:
a.sort()

In [9]:
a

array([1, 2, 4, 8, 9])

#### » Creating an array with values sampled from a `normal (Gaussian) distribution`

In [12]:
b = np.random.normal(10,5,(2,2))

In [13]:
b

array([[ 8.26180407, -1.58801288],
       [10.0637584 ,  8.18423894]])

#### » Sorting a 2D array along columns (axis=0)

In [14]:
np.sort(b, axis=0)

array([[ 8.26180407, -1.58801288],
       [10.0637584 ,  8.18423894]])

#### » Sorting a 2D array along rows (axis=1)

In [18]:
np.sort(b, axis=1)

array([[-1.58801288,  8.26180407],
       [ 8.18423894, 10.0637584 ]])

#### » Sorting by multiple keys

In [22]:
names = np.array(['Amanda', 'Alice', 'Joe'])
grades = np.array([85, 90, 85])
np.sort((names, grades))  

array([['Alice', 'Amanda', 'Joe'],
       ['85', '85', '90']], dtype='<U21')