In [1]:
import numpy as np

In [2]:
a = np.array([1,2,3,4,5,6,7,8])

In [3]:
a

array([1, 2, 3, 4, 5, 6, 7, 8])

In [5]:
np.split(a, [3,5])

[array([1, 2, 3]), array([4, 5]), array([6, 7, 8])]

In [6]:
x, y, z = np.split(a, [3,5])

In [7]:
x

array([1, 2, 3])

In [8]:
y

array([4, 5])

In [9]:
z

array([6, 7, 8])

In [10]:
a = np.arange(16).reshape(4,4)

In [11]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [14]:
np.vsplit(a, [2])

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])]

In [16]:
top, bottom = np.vsplit(a, [2])

In [17]:
top

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [18]:
bottom

array([[ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [15]:
np.hsplit(a, [2])

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]

In [19]:
right, left = np.hsplit(a, [2])

In [20]:
right

array([[ 0,  1],
       [ 4,  5],
       [ 8,  9],
       [12, 13]])

In [22]:
left

array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15]])