# ✂️ NumPy Array Splitting

#### » Importing the NumPy library, usually abbreviated as `np`

In [6]:
import numpy as np

#### » Creating 1D array

In [7]:
a = np.array([1,2,3,4,5,6,7,8])

In [8]:
a

array([1, 2, 3, 4, 5, 6, 7, 8])

In [9]:
#### » Splitting a 1D array into 3 equal parts

In [10]:
np.split(a, [3,5])

[array([1, 2, 3]), array([4, 5]), array([6, 7, 8])]

In [11]:
x, y, z = np.split(a, [3,5])

In [12]:
x

array([1, 2, 3])

In [13]:
y

array([4, 5])

In [14]:
z

array([6, 7, 8])

#### » Creating a 1D array and reshaping it to 2D

In [15]:
a = np.arange(16).reshape(4,4)

In [16]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

#### » Splitting a 2D array into 2 along rows (vertical)

In [28]:
np.vsplit(a, 2)

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])]

In [29]:
top, bottom = np.vsplit(a, 2)

In [30]:
top

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [31]:
bottom

array([[ 8,  9, 10, 11],
       [12, 13, 14, 15]])

#### » Splitting a 2D array into 2 along columns (horizontal)

In [26]:
np.hsplit(a, 2)

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]

In [33]:
right, left = np.hsplit(a, 2)

In [34]:
right

array([[ 0,  1],
       [ 4,  5],
       [ 8,  9],
       [12, 13]])

In [35]:
left

array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15]])

#### » Unequal splitting using `array_split`

In [40]:
np.array_split(a, 3)

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11]]),
 array([[12, 13, 14, 15]])]